---

# Ajout du compte user-ansible dans le groupe www-data pour la gestion des droits sur l'arborescence mediawiki
- name: "add user-ansible"
  command:
    usermod -a -G www-data user-ansible

# Creation du repertoire pour l'installation des fichier Mediawiki
- name: "mediawiki diretory"
  file:
    path: "{{mediawiki_directory}}"
    owner: "www-data"
    group: "www-data"
    state: directory

# Decompresse le fichier source archive Mediawiki et le formate sans extension
- name: "uncompress mediawiki archive"
  unarchive:
    src: "{{mediawiki_archive_url}}"
    dest: "{{mediawiki_directory}}"
    owner: "www-data"
    group: "www-data"
    remote_src: yes
    # supprime mediawiki-1.xx.x/ du path
    extra_opts: --transform=s/mediawiki-[0-9\.]*\///

# Ajoute les droits d'ecriture pour le groupe www-data
- name: "add g+w sur le repertoire mediawiki"
  command:
    chmod -R g+w {{mediawiki_directory}}

# Execute la tache avec l'user-ansible, se place dans le repertoire de maintenance et 
# execute la commande de configuration sir le fichier LocalSettings.php n'existe pas
- name: "mediawiki configuration"
  become: yes
  become_user: "user-ansible"
  args:
    creates: "{{mediawiki_directory}}/LocalSettings.php"
    chdir: "{{mediawiki_maintenance_directory}}"
  command:
    php install.php --scriptpath /{{mediawiki_name}}
    --dbname mediawiki --lang fr
    --dbuser {{mediawiki_db_user}}
    --dbpass {{mediawiki_db_password}}
    --pass {{mediawiki_admin_password}}
    --dbserver {{mediawiki_db_host}}
    --server http://http1
    {{mediawiki_title}} {{mediawiki_admin_user}}
  run_once: yes
  delegate_to: "{{item}}"
  with_items: "{{groups.apache}}"

# Execute la tache avec l'user-ansible, se place dans le repertoire de maintenance et execute la commande de mise a jour de la base une seule fois
- name: "mediawiki db update"
  become: yes
  become_user: "user-ansible"
  command:
    php update.php --quick
  args:
    chdir: "{{mediawiki_maintenance_directory}}"
  # La mise a jour a besoin d'etre lancee une seule fois
  run_once: yes
  register: resultat
  changed_when: "'Done in' in resultat.stdout"
